consumer:
    image: matteosister/elixir:1.0.5
    links:
        - rabbitmq
    volumes:
        - .:/app
    working_dir: /app

rabbitmq:
    image: rabbitmq:3-management
    ports:
        - "25672:15672"
